version: "3.9"
   
services:
  postgres-db:
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
  
  backend:
    volumes:
      - ./app-config.local.docker.yaml:/app/app-config.local.docker.yaml
    ports:
      - "7007:7007"
  
  frontend:
    ports:
      - "3000:80"