version: "3.9"
   
services:
  postgres-db:
    image: postgres
    restart: always
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
        interval: 10s
        timeout: 5s
        retries: 10
    networks:
      - backstage
  
  backend:
    build:
      context: ../
      dockerfile: backstage-local/Dockerfile.local.backend
    restart: always
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - backstage

  frontend:
    build:
      context: ../
      dockerfile: backstage-local/Dockerfile.local.frontend
    restart: always
    depends_on:
      - backend
    networks:
      - backstage

networks:
  backstage: